export const data = {
  delhi: "DEL",
  paris: "PAR",
  lyon: "LYS",
  marseille: "MRS",
  toulouse: "TLS",
  strasbourg: "SXB",
  nice: "NCE",
  bordeaux: "BOD",
  lille: "LIL",
  nantes: "NTE",
  montpellies: "MPL",
  rennes: "RNS",
  avignon: "AVN",
  dijon: "DIJ",
  rouen: "URO",
  reims: "RHE",
  grenoble: "GNB",
  metz: "ETZ",
  laRochelle: "LRH",
  saintEtienne: "EBU",
  clermontFerrand: "CFE",
};

export const people = [
  {
    id: 1,
    name: "susan smith",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-1.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 2,
    name: "anna johnson",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-2.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 3,
    name: "peter jones",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-4.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 4,
    name: "bill anderson",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-3.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 5,
    name: "bill anderson",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-5.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 1,
    name: "susan smith",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-1.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 2,
    name: "anna johnson",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-2.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 3,
    name: "peter jones",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-4.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 4,
    name: "bill anderson",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-3.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 5,
    name: "bill anderson",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-5.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 4,
    name: "bill anderson",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-3.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
  {
    id: 5,
    name: "bill anderson",
    rating: "5.0 amazing",
    image: "https://course-api.com/images/people/person-5.jpeg",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque eos iusto voluptate assumenda mollitia, dicta saepe laudantium corrupti laborum rem suscipit, maiores nam natus placeat sapiente omnis aperiam architecto? Dolorum.",
  },
];
